defaults:
  - _self_
  - problem: agitated-chandan
  - llm_client: openai
  - override hydra/output: local

hydra:
  job:
    name: ${problem.problem_name}
    chdir: True

# The chosen algorithm
algorithm: greedy # other options are "eoh", "ael"; some problems may not support "ael"
# will also be doing dirans for DirectAnswer and other baselines from the CO-Bench paper
# optinos are: reevo, greedy, dir-ans

model: gpt-4.1-mini # this is a hack way of solving this but this line should not be here, also, switching to gpt-4.1-mini because rate limiting

# Main GA loop parameters
max_fe: 100 # maximum number of function evaluations
pop_size: 10 # population size for GA
# init_pop_size: 30 # initial population size for GA
init_pop_size: 25 # changing this to 25 to be less intensive on the LLM model
mutation_rate: 0.5 # mutation rate for GA
timeout: 20 # timeout for evaluation of a single code
diversify_init_pop: True # whether to diversify the initial population