_target_: utils.llm_client.openai.OpenAIClient

# model: gpt-4o-mini # LLM model
model: gpt-4.1-mini # using 4.1 and not 4o-mini because hit requests per day (RPD) rate limit for 4o-mini which is 10,000
temperature: 1.0  # temperature for chat completion
api_key: ${oc.env:OPENAI_API_KEY,null}